# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
# resources:
#   pipelines:
#     - pipeline: backendbuild
#       source: backend-build
#       trigger: true
# trigger:
# - master
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - Rumexstore-angular
    exclude:
    - RumexStore.Dal
    - RumexStore.Models
    - RumexStore.Service
    - RumexStore.Functions.ImageProcessing
pr:
  branches:
    include:
    - master
  paths:
    include:
    - Rumexstore-angular
    exclude:
    - RumexStore.Dal
    - RumexStore.Models
    - RumexStore.Service
    - RumexStore.Functions.ImageProcessing


pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  # - job: waitForValidation
  #   displayName: Wait for external validation
  #   pool: server
  #   timeoutInMinutes: 4320 # job times out in 3 days
  #   steps:
  #   - task: ManualValidation@0
  #     timeoutInMinutes: 1440 # task times out in 1 day
  #     inputs:
  #       notifyUsers: |
  #         ghassan.taher@gmail.com
  #         gtaher@yahoo.com
  #       instructions: 'Please validate the build configuration and resume'
  #       onTimeout: 'resume'
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: |
          echo front end build
          echo Reason - $(Build.Reason)
          echo Source Branch - $(Build.SourceBranch)
          echo Source Branch Name - $(Build.SourceBranchName)

      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Install Node.js 18.x'
      - task: CmdLine@2
        inputs:
          script: |
            echo  '$(System.DefaultWorkingDirectory)'
            echo ----
            dir
      - script: tree $(System.DefaultWorkingDirectory)/rumexstore-angular/
      - script: |
          cd rumexstore-angular/
          echo ----
          dir
          npm install -g @angular/cli
          echo ----
          dir
          npm install
          echo ----
          dir
          ng build --configuration=production
          echo ----
          dir
        displayName: 'npm install and build'
        workingDirectory: '$(Build.SourcesDirectory)'
      - task: CmdLine@2
        displayName: "Run unit tests"
        inputs:
          script: |
            cd rumexstore-angular/
            ng test --browsers=ChromeHeadless --code-coverage --watch=false
      - script: tree $(System.DefaultWorkingDirectory)/rumexstore-angular/dist/
      - script: tree $(System.DefaultWorkingDirectory)/rumexstore-angular/dist/rumexstore-angular/
      - powershell: Get-ChildItem -Path $(System.DefaultWorkingDirectory)/rumexstore-angular/dist/rumexstore-angular\*.* -recurse

      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/rumexstore-angular/dist/rumexstore-angular/'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          ArtifactName: 'frontend-production'
          # publishLocation: 'Container'
