# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# trigger:
#   branches:
#     include:
#       - master
#     exclude:
#       - releases/old*
#   paths:
#     exclude:
#       - rumexstore-angular
trigger:
- master
# trigger:
#   branches:
#     include:
#     - master
#   paths:
#     include:
#     - RumexStore.Dal
#     - RumexStore.Models
#     - RumexStore.Service

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    echo angular build
    echo Reason - $(Build.Reason)
    echo Source Branch - $(Build.SourceBranch)
    echo Source Branch Name - $(Build.SourceBranchName)
    echo Sources Directory - $(Build.SourcesDirectory)
    echo Definition Name - $(Build.DefinitionName)
    echo ----
    echo Work Folder - $(Agent.WorkFolder)
    echo Default Working Directory - $(System.DefaultWorkingDirectory)
    echo Repository LocalPath - $(Build.Repository.LocalPath)
    echo Environment ResourceName - $(Environment.ResourceName)
# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'
