# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
    exclude:
      - releases/old*
  paths:
    exclude:
      - rumexstore-angular/*

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    echo $(Build.Reason)
    echo $(Build.SourceBranch)
    echo $(Agent.WorkFolder)
    echo $(System.DefaultWorkingDirectory)
# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'
